name: Compile Arduino sketch

on:
  workflow_dispatch:

jobs:

  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ESP32 platform dependencies
        run: pip3 install pyserial

      - uses: arduino/compile-sketches@v1.1.0
        with:
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          fqbn: esp32:esp32:esp32
          sketch-paths: |
            - Arduino/WIP/Base
          libraries: |
            - name: ESP8266 Influxdb
            - name: DHT sensor library
            - source-url : https://github.com/ivanseidel/ArduinoThread/archive/refs/tags/2.1.1.zip
            - name: ArduinoJson
