{
 "title": "Chambre",
 "description": "Every information about \"Salon\" room",
 "tags": [
  "temperature",
  "humidity"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Last update",
   "type": "stat",
   "description": "When was the last update receive in \"Salon\" ?",
   "gridPos": { "h": 4, "w": 10, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"My Home\")\n  |> range(start: -24h, stop: now())\n  |> filter(fn: (r) => r[\"Room\"] == \"Chambre\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\n  |> last(column: \"_time\")\n  |> yield(name: \"Last update\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "How many times between now and last update ?",
   "gridPos": { "h": 4, "w": 10, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"My Home\")\n  |> range(start: -24h, stop: now())\n  |> filter(fn: (r) => r[\"Room\"] == \"Chambre\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\n  |> last(column: \"_time\")\n  |> yield(name: \"Last update\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Current temperature",
   "type": "gauge",
   "description": "What is the current temp in \"Salon\" ?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"My Home\")\n  |> range(start: -5m, stop: now())\n  |> filter(fn: (r) => r[\"Room\"] == \"Chambre\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\n  |> last(column: \"_value\")\n  |> yield(name: \"Current temperature\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current humidity",
   "type": "gauge",
   "description": "What is the current humidity in \"Salon\" ?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"My Home\")\n  |> range(start: -5m, stop: now())\n  |> filter(fn: (r) => r[\"Room\"] == \"Chambre\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Humidity\")\n  |> last(column: \"_value\")\n  |> yield(name: \"Current humidity\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Today", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Today temperature",
   "type": "timeseries",
   "description": "What was the temperature over this whole day ?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -24h, stop: now())\n  |> filter(fn: (r) => r[\"Room\"] == \"Chambre\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\n  |> yield(name: \"Temperature\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today humidity",
   "type": "timeseries",
   "description": "What was the himidity over this whole day ?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"My Home\")\n  |> range(start: -24h, stop: now())\n  |> filter(fn: (r) => r[\"Room\"] == \"Chambre\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Humidity\")\n  |> yield(name: \"Humidity\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}